### ISSUE TITLE
execOTA() doesn't return on error

### ISSUE THREAD

**Issue by iMina** [chrisjoyce911/esp32FOTA#9] opened 2019-09-17 19:28 UTC
I am trying to test my OTA, I get the following log :
```
Connecting to: spimesenselabs.com
Fetching Bin: /IoTik/v19.ino.bin
Got a non 200 status code from server. Exiting OTA Update.
contentLength : 0, isValidContentType : 0
There was no content in the response
```
but the function does not return and I have to reboot every time.

**Comment by chrisjoyce911** [comment] 2019-09-17 22:00
Duplicate of #10

**Closed by chrisjoyce911** 2019-09-17 22:00 UTC
Labels: duplicate

**Comment by iMina** [comment] 2019-09-17 22:07
Why is it a duplicate of #10 ?
This one concerns with the function not returning to the calling statement after it finishes.
