### ISSUE TITLE
execHTTPcheck returns unexpected message

### ISSUE THREAD

**Issue by milkywade** [chrisjoyce911/esp32FOTA#120] opened 2022-12-11 19:49 UTC
Hi - thanks for 0.2.6 and 0.2.7!

Using 0.2.7 when I execute the following code:

`bool updatedNeeded = esp32FOTA.execHTTPcheck();`

...I receive this message

`[ 83817][E][WiFiClient.cpp:517] flush(): fail on fd 48, errno: 11, "No more processes"`

...whether the result of the check is true or false.

Any ideas please ?

**Comment by tobozo** [comment] 2022-12-11 20:08
Hi,

This seems [related to sketches with low (under 40kb) heap](https://github.com/search?q=WiFiClient.cpp+flush+fail+errno+11+%22No+more+processes%22&type=issues), probably not caused by esp32FOTA unless there''s a memory leak somewhere.

closing this as out of scope

feel free to reopen if you know it's a mem leak

**Closed by tobozo** 2022-12-11 20:08 UTC
